// <auto-generated />
using System;
using Divisima.DataAccess.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Divisima.Dal.Migrations
{
    [DbContext(typeof(DivisimaDbContext))]
    partial class DivisimaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Divisima.Entity.Entities.Address", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("city");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("district");

                    b.Property<string>("full_address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("full_address");

                    b.Property<string>("full_name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("is_default")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("zip_code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("zip_code");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.AuditLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("action");

                    b.Property<string>("changes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("changes");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("entity_id")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("entity_id");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("table_name");

                    b.Property<string>("user_id")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.HasIndex("table_name", "created_at");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Cart", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("reminder_sent_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("reminder_sent_at");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.CartItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cart_id")
                        .HasColumnType("int")
                        .HasColumnName("cart_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("size");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("cart_id");

                    b.HasIndex("cart_id", "product_id", "size")
                        .IsUnique()
                        .HasFilter("[is_active] = 1");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("display_order")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Collection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte>("collection_type")
                        .HasColumnType("tinyint")
                        .HasColumnName("collection_type");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("curator_name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("curator_name");

                    b.Property<string>("gradient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("gradient");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("slug");

                    b.Property<string>("subtitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("subtitle");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.CollectionItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("collection_id")
                        .HasColumnType("int")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("display_order")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("id");

                    b.HasIndex("collection_id", "product_id")
                        .IsUnique();

                    b.ToTable("collection_items", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ConsentRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("consent_type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("document_version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("granted")
                        .HasColumnType("bit");

                    b.Property<string>("ip_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_agent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("customer_id", "consent_type");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Content", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("body_en")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_en");

                    b.Property<string>("body_tr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_tr");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<string>("title_en")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title_en");

                    b.Property<string>("title_tr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title_tr");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("slug")
                        .IsUnique();

                    b.ToTable("contents", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Coupon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("code");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<byte>("discount_type")
                        .HasColumnType("tinyint")
                        .HasColumnName("discount_type");

                    b.Property<DateTime?>("expire_date")
                        .HasColumnType("datetime2")
                        .HasColumnName("expire_date");

                    b.Property<bool>("first_order_only")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("first_order_only");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("max_discount_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_discount_amount");

                    b.Property<decimal>("min_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_amount");

                    b.Property<int>("per_user_limit")
                        .HasColumnType("int");

                    b.Property<byte[]>("row_version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("usage_limit")
                        .HasColumnType("int")
                        .HasColumnName("usage_limit");

                    b.Property<int>("used_count")
                        .HasColumnType("int")
                        .HasColumnName("used_count");

                    b.Property<decimal>("value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.CouponUsage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("coupon_id")
                        .HasColumnType("int")
                        .HasColumnName("coupon_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("discount_applied")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_applied");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.HasKey("id");

                    b.ToTable("coupon_usages", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("birthdate")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthdate");

                    b.Property<DateTime?>("birthday_offer_sent_year")
                        .HasColumnType("datetime2")
                        .HasColumnName("birthday_offer_sent_year");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("email_verification_sent_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("email_verification_sent_at");

                    b.Property<string>("email_verification_token")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("email_verification_token");

                    b.Property<bool>("email_verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<int>("failed_login_attempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_attempts");

                    b.Property<int?>("gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("last_login_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_order_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_order_at");

                    b.Property<DateTime?>("last_winback_sent_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_winback_sent_at");

                    b.Property<DateTime?>("lockout_end")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_end");

                    b.Property<int>("loyalty_points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("loyalty_points");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("notify_email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_email");

                    b.Property<bool>("notify_push")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_push");

                    b.Property<bool>("notify_sms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("notify_sms");

                    b.Property<byte[]>("password_hash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("password_reset_expiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_expiry");

                    b.Property<string>("password_reset_token")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("password_reset_token");

                    b.Property<byte[]>("password_salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("referral_code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("referral_code");

                    b.Property<int?>("referred_by")
                        .HasColumnType("int")
                        .HasColumnName("referred_by");

                    b.Property<decimal>("store_credit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("store_credit");

                    b.Property<string>("two_factor_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("two_factor_code_expiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("two_factor_enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("two_factor_secret")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<byte>("user_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("referral_code")
                        .IsUnique()
                        .HasFilter("[referral_code] IS NOT NULL");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.CustomerDevice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("device_token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("device_token");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("last_used_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_used_at");

                    b.Property<byte>("platform")
                        .HasColumnType("tinyint")
                        .HasColumnName("platform");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("device_token")
                        .IsUnique();

                    b.ToTable("customer_devices", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.GiftCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("initial_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("initial_amount");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("redeemed_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("redeemed_at");

                    b.Property<int?>("redeemed_by")
                        .HasColumnType("int")
                        .HasColumnName("redeemed_by");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("gift_cards", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Invoice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("company_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("invoice_number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("invoice_number");

                    b.Property<byte>("invoice_type")
                        .HasColumnType("tinyint");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("pdf_url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("pdf_url");

                    b.Property<string>("provider_invoice_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("tax_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<string>("tax_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tax_rate")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("invoice_number")
                        .IsUnique();

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.LoyaltyTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<byte>("type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.HasIndex("customer_id", "created_at");

                    b.ToTable("loyalty_transactions", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("address_id")
                        .HasColumnType("int")
                        .HasColumnName("address_id");

                    b.Property<string>("coupon_code")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("TRY")
                        .HasColumnName("currency");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("delivered_at")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<byte>("installment_count")
                        .HasColumnType("tinyint");

                    b.Property<bool>("is_online_payment_done")
                        .HasColumnType("bit")
                        .HasColumnName("is_online_payment_done");

                    b.Property<string>("order_number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("order_number");

                    b.Property<string>("payment_id")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("payment_id");

                    b.Property<byte>("payment_type")
                        .HasColumnType("tinyint")
                        .HasColumnName("payment_type");

                    b.Property<string>("request_id")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("request_id");

                    b.Property<DateTime?>("review_invite_sent_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("review_invite_sent_at");

                    b.Property<decimal>("shipping_cost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_cost");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<decimal>("store_credit_used")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("order_number")
                        .IsUnique();

                    b.HasIndex("request_id")
                        .IsUnique()
                        .HasFilter("[request_id] IS NOT NULL");

                    b.HasIndex("customer_id", "created_at");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.OrderItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_cancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cancelled");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("seller_id")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("size");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.HasIndex("seller_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.OrderSnapshot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("coupon_code")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("coupon_code");

                    b.Property<string>("customer_full_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("customer_full_name");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<decimal>("discount_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime>("order_created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("shipping_address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("shipping_address");

                    b.Property<decimal>("shipping_cost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("shipping_cost");

                    b.Property<DateTime>("snapshot_created_at")
                        .HasColumnType("datetime2");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("total_price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("order_snapshots", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.OrderSnapshotItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("brand");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("order_snapshot_id")
                        .HasColumnType("int")
                        .HasColumnName("order_snapshot_id");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("product_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("product_name");

                    b.Property<decimal>("product_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("size");

                    b.HasKey("id");

                    b.ToTable("order_snapshot_items", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.ToTable("order_status_histories", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.OutboxMessage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("error")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("error");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<int>("retry_count")
                        .HasColumnType("int")
                        .HasColumnName("retry_count");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.HasIndex("status", "created_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("conversation_id")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("fraud_status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fraud_status");

                    b.Property<byte>("installment_count")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("installment_fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("paid_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<decimal?>("paid_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_price");

                    b.Property<string>("payment_provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("payment_provider");

                    b.Property<byte>("payment_status")
                        .HasColumnType("tinyint")
                        .HasColumnName("payment_status");

                    b.Property<string>("token")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("token");

                    b.Property<string>("transaction_id")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("transaction_id");

                    b.HasKey("id");

                    b.HasIndex("conversation_id");

                    b.HasIndex("order_id");

                    b.HasIndex("token");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.PriceDropSubscription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("is_notified")
                        .HasColumnType("bit")
                        .HasColumnName("is_notified");

                    b.Property<DateTime?>("notified_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("notified_at");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal>("subscribed_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subscribed_price");

                    b.HasKey("id");

                    b.HasIndex("product_id", "email")
                        .IsUnique()
                        .HasFilter("[is_notified] = 0");

                    b.HasIndex("product_id", "is_notified");

                    b.ToTable("price_drop_subscriptions", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("average_rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("brand");

                    b.Property<int>("category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("color_hex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("image_url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("old_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("old_price");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<byte>("product_type")
                        .HasColumnType("tinyint")
                        .HasColumnName("product_type");

                    b.Property<int>("review_count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("sale_end")
                        .HasColumnType("datetime2")
                        .HasColumnName("sale_end");

                    b.Property<decimal?>("sale_price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sale_price");

                    b.Property<DateTime?>("sale_start")
                        .HasColumnType("datetime2")
                        .HasColumnName("sale_start");

                    b.Property<int?>("seller_id")
                        .HasColumnType("int")
                        .HasColumnName("seller_id");

                    b.Property<int?>("sub_category_id")
                        .HasColumnType("int")
                        .HasColumnName("sub_category_id");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("variant_group_id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("variant_group_id");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("is_active");

                    b.HasIndex("seller_id");

                    b.HasIndex("variant_group_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ProductAttribute", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("attribute_key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("attribute_key");

                    b.Property<string>("attribute_value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attribute_value");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("attribute_key", "attribute_value");

                    b.ToTable("product_attributes", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ProductImage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("is_primary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("sort_order")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ProductQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("answer")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("answer");

                    b.Property<DateTime?>("answered_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("answered_at");

                    b.Property<int?>("answered_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("is_answered")
                        .HasColumnType("bit");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("question");

                    b.HasKey("id");

                    b.HasIndex("product_id", "is_answered");

                    b.ToTable("product_questions", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ProductReview", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("helpful_count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("helpful_count");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("is_verified_purchase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified_purchase");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<byte>("review_status")
                        .HasColumnType("tinyint")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("customer_id", "product_id")
                        .IsUnique()
                        .HasFilter("[is_active] = 1");

                    b.HasIndex("product_id", "review_status");

                    b.ToTable("product_reviews", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ProductStock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("reserved_quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_quantity");

                    b.Property<byte[]>("row_version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("size");

                    b.Property<int>("stock_quantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("product_id", "size")
                        .IsUnique();

                    b.ToTable("product_stocks", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.RecentlyViewedProduct", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("viewed_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("viewed_at");

                    b.HasKey("id");

                    b.HasIndex("customer_id", "product_id")
                        .IsUnique();

                    b.HasIndex("customer_id", "viewed_at");

                    b.ToTable("recently_viewed_products", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ReturnRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("admin_note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("admin_note");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("processed_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<byte>("reason")
                        .HasColumnType("tinyint")
                        .HasColumnName("reason");

                    b.Property<decimal>("refund_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("refund_id")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("refund_id");

                    b.Property<byte>("return_type")
                        .HasColumnType("tinyint")
                        .HasColumnName("return_type");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("size");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("order_id");

                    b.HasIndex("status");

                    b.ToTable("return_requests", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ReviewHelpfulVote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("review_id")
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    b.HasKey("id");

                    b.HasIndex("review_id", "customer_id")
                        .IsUnique();

                    b.ToTable("review_helpful_votes", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.SecurityEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("detail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("event_type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("event_type");

                    b.Property<string>("ip_address")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ip_address");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("user_agent")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("user_agent");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("event_type", "created_at");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Seller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("business_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("business_name");

                    b.Property<decimal>("commission_rate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(10m)
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<int>("failed_login_attempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_attempts");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("lockout_end")
                        .HasColumnType("datetime2")
                        .HasColumnName("lockout_end");

                    b.Property<byte[]>("password_hash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("password_salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("password_salt");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<byte>("status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("status");

                    b.Property<string>("tax_number")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tax_number");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<byte>("user_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)3)
                        .HasColumnName("user_type");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("status");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Shipment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte>("carrier")
                        .HasColumnType("tinyint")
                        .HasColumnName("carrier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("delivered_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("estimated_delivery")
                        .HasColumnType("datetime2")
                        .HasColumnName("estimated_delivery");

                    b.Property<DateTime?>("last_checked_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_checked_at");

                    b.Property<string>("last_status_text")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("last_status_text");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("shipped_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipped_at");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<string>("tracking_number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tracking_number");

                    b.HasKey("id");

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.HasIndex("tracking_number");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.SizeGuideEntry", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("bust_cm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("bust_cm");

                    b.Property<int>("category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("hip_cm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("hip_cm");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("length_cm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("length_cm");

                    b.Property<string>("size_label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("size_label");

                    b.Property<int>("sort_order")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<decimal?>("waist_cm")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("waist_cm");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("size_guide_entries", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.StockMovement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<byte>("movement_type")
                        .HasColumnType("tinyint")
                        .HasColumnName("movement_type");

                    b.Property<string>("note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("note");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("reference_id")
                        .HasColumnType("int")
                        .HasColumnName("reference_id");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("size");

                    b.HasKey("id");

                    b.HasIndex("product_id", "size");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.StockNotificationRequest", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("is_notified")
                        .HasColumnType("bit")
                        .HasColumnName("is_notified");

                    b.Property<DateTime?>("notified_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("notified_at");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("size");

                    b.HasKey("id");

                    b.HasIndex("product_id", "size", "email")
                        .IsUnique()
                        .HasFilter("[is_notified] = 0");

                    b.HasIndex("product_id", "size", "is_notified");

                    b.ToTable("stock_notification_requests", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.StockReservation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("closed_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<int>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("size");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("status", "expires_at");

                    b.ToTable("stock_reservations", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.StoreCreditTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("order_id")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("reason");

                    b.Property<byte>("type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.HasIndex("customer_id", "created_at");

                    b.ToTable("store_credit_transactions", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.SubCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("category_id")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("id");

                    b.HasIndex("category_id", "slug")
                        .IsUnique();

                    b.ToTable("sub_categories", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.UserSession", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("device")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device");

                    b.Property<DateTime>("expires_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("ip_address")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("refresh_token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token");

                    b.HasKey("id");

                    b.HasIndex("customer_id");

                    b.HasIndex("refresh_token");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.WishlistItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("customer_id")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("id");

                    b.HasIndex("customer_id", "product_id")
                        .IsUnique();

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Address", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Cart", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Divisima.Entity.Entities.CartItem", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Cart", null)
                        .WithMany()
                        .HasForeignKey("cart_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Divisima.Entity.Entities.Order", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Divisima.Entity.Entities.OrderItem", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Divisima.Entity.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Divisima.Entity.Entities.ProductReview", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Divisima.Entity.Entities.WishlistItem", b =>
                {
                    b.HasOne("Divisima.Entity.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("customer_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
